### ISSUE TITLE
Live:  sort recipients by rank impossible

### ISSUE THREAD

**Issue by bagage** [osmandapp/osmandapp.github.io#130]
Since all contributors that did not do any changes this month are ranked at level 0, then at level 20, then 19 .. to finish at level 1 for biggest contributors, it's impossible to see the biggest contributors easily on the website.

Could it be possible that either:

- users who did not contribute yet have no rank assigned to or
- users who did not contribute have a rank of 21 or anything > than 20? or
- a custom sort is used to sort the rank column to have (rank 1...20 then 0), so that we can see who are the biggest contributors easily?
- ranks are inverted so that people with the biggest rank are the biggest contributors?

**Comment by vshcherb** [comment]
<img width="1107" alt="screen shot 2018-07-31 at 22 34 05" src="https://user-images.githubusercontent.com/1042025/43485569-dc9f7a8c-9511-11e8-9169-ac62f621425d.png">

- It is not possible to see worldwide because it is too many contributors
- Highest rank mins the biggest contributors. 
- Users who contributed < 3 are not in the ranking system
- You can see & sort contributors only by country
